version: '3.7'

services:
  express:
    build: .
    container_name: evgeniy-express-app
    volumes:
      - .:/app:cached
      - logs:/app/logs
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      PORT: ${PORT}
    restart: always
    networks:
      - user_network
    command: npm run start

  db:
    image: postgres:11.4
    container_name: evgeniy-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - user_network

networks:
  user_network:
    driver: bridge

volumes:
  db_data:
  logs:
